const Produtos = [
    { id: 1, nome: "Teclado Gamer", categoria: "Periféricos", preco: 120.00 },
    { id: 2, nome: "Mouse Sem Fio", categoria: "Periféricos", preco: 89.90 },
    { id: 3, nome: "Monitor 24 Polegadas", categoria: "Monitores", preco: 799.90 },
    { id: 4, nome: "Headset USB", categoria: "Áudio", preco: 149.90 },
    { id: 5, nome: "Notebook", categoria: "Computadores", preco: 3299.90 },
    { id: 6, nome: "Webcam HD", categoria: "Acessórios", preco: 199.90 },

    { id: 7, nome: "Mousepad RGB", categoria: "Periféricos", preco: 59.90 },
    { id: 8, nome: "Caixa de Som Bluetooth", categoria: "Áudio", preco: 229.90 },
    { id: 9, nome: "Impressora Multifuncional", categoria: "Impressoras", preco: 649.90 },
    { id: 10, nome: "SSD 1TB", categoria: "Armazenamento", preco: 499.90 },
    { id: 11, nome: "HD Externo 2TB", categoria: "Armazenamento", preco: 389.90 },
    { id: 12, nome: "Placa de Vídeo RTX 4060", categoria: "Componentes", preco: 2599.90 },
    { id: 13, nome: "Memória RAM 16GB", categoria: "Componentes", preco: 329.90 },
    { id: 14, nome: "Processador Ryzen 7", categoria: "Componentes", preco: 1899.90 },
    { id: 15, nome: "Gabinete Gamer", categoria: "Componentes", preco: 449.90 },
    { id: 16, nome: "Fonte 750W", categoria: "Componentes", preco: 599.90 },
    { id: 17, nome: "Cooler RGB", categoria: "Componentes", preco: 149.90 },
    { id: 18, nome: "Cadeira Gamer", categoria: "Móveis", preco: 1299.90 },
    { id: 19, nome: "Mesa para Escritório", categoria: "Móveis", preco: 799.90 },
    { id: 20, nome: "Tablet 10 Polegadas", categoria: "Tablets", preco: 1599.90 },
    { id: 21, nome: "Smartphone Android", categoria: "Celulares", preco: 2199.90 },
    { id: 22, nome: "Carregador Turbo USB-C", categoria: "Acessórios", preco: 99.90 },
    { id: 23, nome: "Cabo HDMI 2m", categoria: "Acessórios", preco: 39.90 },
    { id: 24, nome: "Suporte para Notebook", categoria: "Acessórios", preco: 89.90 },
    { id: 25, nome: "Hub USB 4 Portas", categoria: "Acessórios", preco: 79.90 },
    { id: 26, nome: "Roteador Wi-Fi 6", categoria: "Redes", preco: 499.90 },
    { id: 27, nome: "Switch 8 Portas", categoria: "Redes", preco: 219.90 },
    { id: 28, nome: "Câmera de Segurança", categoria: "Segurança", preco: 349.90 },
    { id: 29, nome: "Microfone Condensador", categoria: "Áudio", preco: 279.90 },
    { id: 30, nome: "Monitor Ultrawide", categoria: "Monitores", preco: 1899.90 },
    { id: 31, nome: "Teclado Mecânico", categoria: "Periféricos", preco: 399.90 },
    { id: 32, nome: "Mouse Gamer RGB", categoria: "Periféricos", preco: 249.90 },
    { id: 33, nome: "Fone Bluetooth", categoria: "Áudio", preco: 199.90 },
    { id: 34, nome: "Smartwatch", categoria: "Wearables", preco: 899.90 },
    { id: 35, nome: "Drone com Câmera", categoria: "Drones", preco: 2499.90 },
    { id: 36, nome: "Projetor Full HD", categoria: "Projetores", preco: 1799.90 },
    { id: 37, nome: "Scanner Portátil", categoria: "Impressoras", preco: 599.90 },
    { id: 38, nome: "Estabilizador 500VA", categoria: "Energia", preco: 299.90 },
    { id: 39, nome: "Nobreak 1200VA", categoria: "Energia", preco: 899.90 },
    { id: 40, nome: "Leitor Biométrico", categoria: "Segurança", preco: 259.90 },
    { id: 41, nome: "Controle Gamer", categoria: "Games", preco: 299.90 },
    { id: 42, nome: "Console Xbox", categoria: "Games", preco: 4299.90 },
    { id: 43, nome: "PlayStation 5", categoria: "Games", preco: 4699.90 },
    { id: 44, nome: "Notebook Gamer", categoria: "Computadores", preco: 6599.90 },
    { id: 45, nome: "MacBook Air", categoria: "Computadores", preco: 8999.90 },
    { id: 46, nome: "iPad Pro", categoria: "Tablets", preco: 7299.90 },
    { id: 47, nome: "Apple Watch", categoria: "Wearables", preco: 3299.90 },
    { id: 48, nome: "Kindle Paperwhite", categoria: "Leitores Digitais", preco: 699.90 },
    { id: 49, nome: "Smart TV 50 Polegadas", categoria: "TVs", preco: 2799.90 },
    { id: 50, nome: "Soundbar", categoria: "Áudio", preco: 999.90 },
    { id: 51, nome: "Mini PC", categoria: "Computadores", preco: 2499.90 },
    { id: 52, nome: "Placa Mãe B550", categoria: "Componentes", preco: 899.90 },
    { id: 53, nome: "Ventoinha Cooler 120mm", categoria: "Componentes", preco: 49.90 },
    { id: 54, nome: "Adaptador Bluetooth", categoria: "Acessórios", preco: 69.90 },
    { id: 55, nome: "Dock Station USB-C", categoria: "Acessórios", preco: 399.90 },
    { id: 56, nome: "Luminária LED", categoria: "Casa", preco: 129.90 },
]

export default Produtos;